### ISSUE TITLE
Does this flatpak need the network permission? 

### ISSUE THREAD

**Issue by uncivilgentleman** [flathub/org.gnome.GTG#1]
I noticed that by default this flatpak has network permissions but as far as I know it doesn't use it.  Does the permission serve any purpose?

Just wondering.  Thanks for the great application :)

**Comment by nekohayo** [comment]
Hmm, well it doesn't use it at the moment, but there were quite a few plugins/backends that used to interact with online resources (for synchronization or importing for example), and I suspect this will be useful again as people implement new sync plugins in the medium term.
